import { createAtomicStyles, createAtomsFn } from '@vanilla-extract/sprinkles'

import { vars } from './theme.css'
import { getColor } from './utils'

const colors = {
  ...vars.color,
  accent: getColor(vars.theme.color.accent),
  accentSecondary: getColor(
    vars.theme.color.accent,
    vars.theme.shade.accentSecondary,
  ),
  background: getColor(vars.theme.color.background),
  backgroundSecondary: getColor(vars.theme.color.backgroundSecondary),
  backgroundTertiary: getColor(vars.theme.color.backgroundTertiary),
  foreground: getColor(vars.theme.color.foreground),
  foregroundSecondary: getColor(
    vars.theme.color.foreground,
    vars.theme.shade.foregroundSecondary,
  ),
  groupBackground: getColor(vars.theme.color.groupBackground),
  groupBorder: getColor(
    vars.theme.color.groupBorder,
    vars.theme.shade.groupBorder,
  ),
  text: getColor(vars.theme.color.foreground, vars.theme.shade.text),
  textSecondary: getColor(
    vars.theme.color.foreground,
    vars.theme.shade.textSecondary,
  ),
  textTertiary: getColor(
    vars.theme.color.foreground,
    `calc(${vars.theme.shade.text} * 0.66)`,
  ),
  // accents
  blue: getColor(vars.theme.color.blue),
  green: getColor(vars.theme.color.green),
}

const responsiveStyles = createAtomicStyles({
  conditions: {
    sm: {},
    md: { '@media': '(min-width: 768px)' },
    lg: { '@media': '(min-width: 1024px)' },
    xl: { '@media': '(min-width: 1280px)' },
  },
  defaultCondition: 'sm',
  properties: {
    alignItems: [
      'baseline',
      'center',
      'flex-end',
      'flex-start',
      'inherit',
      'initial',
      'stretch',
    ],
    background: colors,
    borderBottomWidth: vars.borderWidth,
    borderLeftWidth: vars.borderWidth,
    borderRightWidth: vars.borderWidth,
    borderTopWidth: vars.borderWidth,
    borderWidth: vars.borderWidth,
    bottom: vars.space,
    color: colors,
    display: ['block', 'flex', 'grid', 'inline-block', 'inline-flex', 'none'],
    flexDirection: ['column', 'row'],
    fontFamily: vars.fontFamily,
    fontSize: vars.fontSize,
    fontWeight: vars.fontWeight,
    gap: vars.space,
    height: vars.space,
    inset: vars.space,
    justifyContent: [
      'center',
      'flex-end',
      'flex-start',
      'inherit',
      'initial',
      'space-around',
      'space-between',
      'space-evenly',
    ],
    left: vars.space,
    letterSpacing: vars.letterSpacing,
    lineHeight: vars.lineHeight,
    margin: vars.space,
    marginBottom: vars.space,
    marginLeft: vars.space,
    marginRight: vars.space,
    marginTop: vars.space,
    maxHeight: vars.space,
    maxWidth: vars.space,
    minHeight: vars.space,
    minWidth: vars.space,
    opacity: vars.opacity,
    overflow: ['hidden'],
    paddingBottom: vars.space,
    paddingLeft: vars.space,
    paddingRight: vars.space,
    paddingTop: vars.space,
    position: ['absolute', 'fixed', 'relative'],
    right: vars.space,
    textAlign: ['center', 'left', 'right'],
    top: vars.space,
    verticalAlign: ['middle'],
    whiteSpace: [
      'normal',
      'nowrap',
      'pre',
      'pre-line',
      'pre-wrap',
      'initial',
      'inherit',
    ],
    wordWrap: ['normal', 'break-word', 'initial', 'inherit'],
    width: vars.space,
  },
  shorthands: {
    b: [
      'borderBottomWidth',
      'borderLeftWidth',
      'borderRightWidth',
      'borderTopWidth',
    ],
    bb: ['borderBottomWidth'],
    bl: ['borderLeftWidth'],
    br: ['borderRightWidth'],
    bt: ['borderTopWidth'],
    bx: ['borderLeftWidth', 'borderRightWidth'],
    by: ['borderBottomWidth', 'borderTopWidth'],
    h: ['height'],
    insetX: ['left', 'right'],
    insetY: ['bottom', 'top'],
    m: ['marginTop', 'marginBottom', 'marginLeft', 'marginRight'],
    mb: ['marginBottom'],
    ml: ['marginLeft'],
    mr: ['marginRight'],
    mt: ['marginTop'],
    mx: ['marginLeft', 'marginRight'],
    my: ['marginTop', 'marginBottom'],
    p: ['paddingTop', 'paddingBottom', 'paddingLeft', 'paddingRight'],
    pb: ['paddingBottom'],
    pl: ['paddingLeft'],
    pr: ['paddingRight'],
    pt: ['paddingTop'],
    px: ['paddingLeft', 'paddingRight'],
    py: ['paddingTop', 'paddingBottom'],
    w: ['width'],
  },
})

const styles = createAtomicStyles({
  properties: {
    cursor: ['not-allowed', 'pointer'],
    strokeWidth: vars.borderWidth,
  },
})

export const atoms = createAtomsFn(responsiveStyles, styles)

export type Atoms = Parameters<typeof atoms>[0]
