const { VanillaExtractPlugin } = require('@vanilla-extract/webpack-plugin')
const MiniCssExtractPlugin = require('mini-css-extract-plugin')

const path = require('path')

module.exports = {
  components: './src/components.ts',
  baseUrl: '/playroom/',
  outputPath: '../docs/public/playroom',
  title: 'Mirror',
  snippets: './src/snippets.ts',
  themes: './src/themes.ts',
  frameComponent: './src/FrameComponent.tsx',
  scope: './src/useScope.ts',
  typeScriptFiles: ['../components/src/**/*.{ts,tsx}'],
  widths: [320, 640, 768, 1024, 1280],
  openBrowser: false,
  port: 8082,
  iframeSandbox: 'allow-scripts allow-same-origin',

  webpackConfig: () => ({
    plugins: [
      new VanillaExtractPlugin(),
      new MiniCssExtractPlugin({
        ignoreOrder: true,
      }),
    ],
    module: {
      rules: [
        {
          test: /\.vanilla\.css$/i, // Targets only CSS files generated by vanilla-extract
          use: [
            MiniCssExtractPlugin.loader,
            {
              loader: require.resolve('css-loader'),
              options: {
                url: false, // Required as image imports should be handled via JS/TS import statements
              },
            },
          ],
        },
        {
          test: /\.tsx?$/,
          exclude: /node_modules/,
          use: {
            loader: 'babel-loader',
            options: {
              presets: [
                '@babel/preset-env',
                '@babel/preset-typescript',
                '@babel/preset-react',
              ],
              plugins: ['@vanilla-extract/babel-plugin'],
            },
          },
        },
      ],
    },
    resolve: {
      alias: {
        degen: path.resolve(__dirname, '../components/src'),
      },
      extensions: ['.js', '.ts', '.tsx'],
    },
  }),
}
